Data crawling
be9904/OSS_Collab pull request #21
Opened 2021-05-23 10:18 UTC by be9904

script 폴더를 생성하여 js 파일들을 전부 이동시켰습니다
crawl.js는 크롤링한 object가 있는 파일, main.js는 기존의 backend.js파일의 이름을 변경한 것이고, bundle.js는 웹브라우저에서도 https모듈을 이용할 수 있도록 하기위한 파일입니다.

그런데 계속해서 크롬을 통해 실행하면 콘솔창에 이런 오류가 뜨는데 혹시 이거 어떻게 해결하나요..
아무리 찾아보고 코드 고쳐도 오류가 그대로 남아있네요ㅜㅜ

<img width="1440" alt="스크린샷 2021-05-23 오후 7 18 29" src="https://user-images.githubusercontent.com/61895947/119256423-adae5180-bbfb-11eb-9b07-be32eaacc012.png">

2021-05-23 11:08 UTC, ChanuYu commented on index.html
> -+
이거 제가 전에 커밋할 때 저도 모르는 사이에 붙인 건데 지워주세요!

2021-05-23 11:08 UTC, ChanuYu commented on package.json
> -    "node-html-parser": "^3.3.0"
이것도 나중에 지워주세요

2021-05-23 11:28 UTC, ChanuYu commented on scripts/main.js
> -
#18 참조하시면 알겠지만 제가 기능을 많이 바꿔놔서 이 부분을 먼저 해결해주셔야 할 거 같습니다!

2021-05-23 12:00 UTC, ChanuYu requested changes
data crawling 부분은 다시 생각해봐야 할 거 같습니다

2021-05-24 05:58 UTC, be9904 commented
교수님께서 답변을 주셨습니다

https.get에 header 매개변수를 삭제했을 때의 결과에 대한 답변 내용입니다.
위의 사진은 원래는 동작해야되는게 정상이라고 하시네요,,

> 아무 헤더도 주지 않고 요청을 했을 때 콘솔에 CORS 오류가 발생하고 있습니다. 이건 요청을 했을 때 응답이 문제 없이 날아오는데 응답 내용이 올바르지 않아서 user-agent를 세팅하는 경우와 다른 경우입니다. 브라우저 보안 정책으로 인해 아예 응답을 받아오지 못하고 있습니다. 일반적으로 웹 브라우저는 임의의 주소에 요청을 보내는 것을 보안 이슈 때문에 막습니다. 즉 지금 상태로는, user-agent를 세팅해서 요청을 하더라도 브라우저에서 막아서 제대로 동작하지 않을겁니다. CORS를 우회하는 방법을 알아보거나 node에서 실행해야 할 듯 합니다.

2021-05-25 04:32 UTC, closed without merging